"""Regression test for the portal-side vault-launch fixture (Brick 6a).

The portal's TS implementation of the new-vault launch builder
(``vault-launch-spend.service.ts``) is validated against a JSON fixture
generated by ``scripts/dump_vault_launch_fixtures.py``.  The fixture lives
in the portal repo at
``solslot-portal/src/app/services/vault-launch.fixtures.json``.

This test re-runs the generator and asserts the on-disk file matches, so
any change to ``vault_driver.py`` that would affect the TS port surfaces
here as a fixture diff (forcing a regeneration + portal-test update).  The
fixture file IS the cross-repo contract between Python and TS.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_REPO_ROOT / "scripts"))

import dump_vault_launch_fixtures  # noqa: E402


def test_fixture_matches_committed_file() -> None:
    """The on-disk fixture must equal what the generator produces now."""
    expected = dump_vault_launch_fixtures.build_fixture()
    fixture_path = dump_vault_launch_fixtures.fixture_destination()
    if not fixture_path.exists():
        pytest.fail(
            f"Portal fixture file is missing at {fixture_path}.\n"
            "Run `scripts/dump_vault_launch_fixtures.py` to regenerate it."
        )
    on_disk = json.loads(fixture_path.read_text())
    assert on_disk == expected, (
        "Portal vault-launch fixture is out of sync with the Python helpers.\n"
        "Run `python scripts/dump_vault_launch_fixtures.py` and commit the diff."
    )


def test_vault_inner_mod_hash_is_a_known_constant() -> None:
    """The vault CODE mod hash MUST be the registry-published value.

    A new vault is launched at this code; if it drifts from what the
    on-chain vault-version registry advertises, the upgrade would launch
    a non-canonical vault.  This pins the value the portal embeds.
    """
    fixture = dump_vault_launch_fixtures.build_fixture()
    expected_vault_inner_mod_hash = (
        "0x81f11be807b668455ce4139dbd71e1303bb1048259cd1416c2a8bc88e27c9c87"
    )
    assert fixture["constants"]["vault_inner_mod_hash"] == expected_vault_inner_mod_hash, (
        "vault_singleton_inner.clsp mod hash drifted!\n"
        f"  expected: {expected_vault_inner_mod_hash}\n"
        f"  got:      {fixture['constants']['vault_inner_mod_hash']}\n"
        "If intentional, re-publish the vault-version registry, update the "
        "portal's VAULT_SINGLETON_INNER_PUZZLE_HEX + environment.vaultInnerModHash, "
        "and bump this expected value."
    )


def test_vault_hex_module_matches_committed_file() -> None:
    """The committed portal vault-code hex module must equal the generator's.

    The new-vault launch builder curries this exact serialized puzzle; if it
    drifts from the live ``VAULT_INNER_MOD`` the portal would launch a vault
    at non-canonical code.
    """
    expected = dump_vault_launch_fixtures.build_puzzle_hex_module()
    hex_path = dump_vault_launch_fixtures.puzzle_hex_destination()
    if not hex_path.exists():
        pytest.fail(
            f"Portal vault hex module is missing at {hex_path}.\n"
            "Run `scripts/dump_vault_launch_fixtures.py` to regenerate it."
        )
    on_disk = hex_path.read_text()
    assert on_disk == expected, (
        "Portal vault-current-inner.puzzle-hex.ts is out of sync with "
        "VAULT_INNER_MOD.  Run `python scripts/dump_vault_launch_fixtures.py` "
        "and commit the diff."
    )


def test_fixture_covers_all_helpers() -> None:
    """Sanity check: each helper category has at least one case."""
    fixture = dump_vault_launch_fixtures.build_fixture()
    assert fixture["constants"], "constants section must be non-empty"
    assert fixture["parse_vault"], "parse_vault cases must be non-empty"
    assert fixture["vault_inner_puzzle_hash"], "vault_inner_puzzle_hash cases must be non-empty"
    assert fixture["vault_full_puzzle_hash"], "vault_full_puzzle_hash cases must be non-empty"
    assert fixture["launch_outputs"], "launch_outputs cases must be non-empty"
