"""Regression test for the portal-side fixture file.

The portal's TS implementation of ``admin_authority_v2_driver`` helpers
(``compute_state_hash``, ``compute_admins_hash`` etc.) is validated
against a JSON fixture generated by ``scripts/dump_v2_fixtures.py``.
That fixture lives in the portal repo at
``solslot-portal/src/app/services/admin-authority-v2/admin-authority-v2.fixtures.json``.

This test re-runs the fixture generator and asserts the on-disk file
matches.  Two reasons:

1. **Stability**: any change to the Python helpers that would affect
   the TS port surfaces here as a fixture diff during ``pytest``,
   forcing a regeneration commit (and thus a portal-side test update).
2. **Cross-repo binding contract**: the fixture file IS the contract
   between Python and TS implementations.  CI keeping it in sync
   prevents silent drift.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

# Add scripts/ to path so we can import the fixture generator.
_REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_REPO_ROOT / "scripts"))

import dump_v2_fixtures  # noqa: E402


def test_fixture_matches_committed_file() -> None:
    """The on-disk fixture must equal what the generator produces now."""
    expected = dump_v2_fixtures.build_fixture()
    fixture_path = dump_v2_fixtures.fixture_destination()
    if not fixture_path.exists():
        pytest.fail(
            f"Portal fixture file is missing at {fixture_path}.\n"
            "Run `scripts/dump_v2_fixtures.py` to regenerate it."
        )
    on_disk = json.loads(fixture_path.read_text())
    assert on_disk == expected, (
        "Portal fixture is out of sync with the Python helpers.\n"
        "Run `python scripts/dump_v2_fixtures.py` and commit the diff."
    )


def test_mod_hash_is_a_known_constant() -> None:
    """The uncurried inner-mod tree hash MUST be the published value.

    Curried into every v2 inner puzzle as ``SELF_MOD_HASH``. Drift
    here would silently make every spend fail the puzzle's own
    self-reference check (the puzzle uses SELF_MOD_HASH to recompute
    its own inner puzzle hash for self-recurry).
    """
    fixture = dump_v2_fixtures.build_fixture()
    # Extracted from the first run of dump_v2_fixtures.py — pinning
    # this catches accidental Chialisp puzzle changes (which would
    # change the bytecode and thus the mod hash).
    expected_mod_hash = (
        "0x811b1ca1ecdf87bdf47aafd4e3f653dc18159b9014f9c76daa42cae76e7a7f3a"
    )
    assert fixture["constants"]["mod_hash"] == expected_mod_hash, (
        f"admin_authority_v2_inner.clsp mod hash drifted!\n"
        f"  expected: {expected_mod_hash}\n"
        f"  got:      {fixture['constants']['mod_hash']}\n"
        f"This means the puzzle source changed.  If intentional, "
        f"update the expected value here AND re-deploy any live "
        f"singletons (the curried SELF_MOD_HASH will no longer match)."
    )


def test_fixture_covers_all_helpers() -> None:
    """Sanity check: each helper category has at least one case.

    Avoids the failure mode where the generator silently emits an
    empty section and the TS port has nothing to validate against.
    """
    fixture = dump_v2_fixtures.build_fixture()
    assert fixture["constants"], "constants section must be non-empty"
    assert fixture["state_hash"], "state_hash cases must be non-empty"
    assert fixture["admins_hash"], "admins_hash cases must be non-empty"
    assert fixture["pending_ops_hash"], "pending_ops_hash cases must be non-empty"
    assert fixture["inner_puzzle_hash"], "inner_puzzle_hash cases must be non-empty"
    assert fixture["roster_update_binding_hash"], (
        "roster_update_binding_hash cases must be non-empty"
    )
    assert fixture["singleton_full_puzzle_hash"], (
        "singleton_full_puzzle_hash cases must be non-empty"
    )
    assert fixture["launch_outputs"], "launch_outputs cases must be non-empty"
