"""Generate explicit inventory fixtures; never overwrite historical fixtures."""
from pathlib import Path
import json
from dataclasses import fields
from chia.types.blockchain_format.program import Program
from chia_rs import AugSchemeMPL
from chia_rs.sized_bytes import bytes32
from solslot_puzzles import load_puzzle
from solslot_puzzles.mint_publish_driver import build_mint_publish_artifacts, PrimaryPurchaseMintConfig
from solslot_puzzles.stripe_settlement_v1_driver import PRIMARY_PURCHASE_PROVIDER_ID
from solslot_puzzles.primary_purchase_v2_driver import PRIMARY_PURCHASE_PROVIDER_ID as HISTORICAL_PROVIDER_ID
from scripts.dump_mint_publish_fixtures import build_fixture


def build_inventory_fixture():
    legacy = build_fixture()
    inputs = dict(legacy["inputs"])
    inputs["protocol_did_singleton_struct_hex"] = legacy["constants"]["protocol_did_singleton_struct_hex"]
    kwargs = {}
    for key, value in inputs.items():
        if key in ("protocol_did_singleton_struct_hex", "governance_singleton_struct_hex"):
            kwargs[key.removesuffix("_hex")] = Program.from_bytes(bytes.fromhex(value[2:]))
        elif key == "jurisdiction_hex": kwargs["jurisdiction"] = bytes.fromhex(value[2:])
        elif isinstance(value, str) and value.startswith("0x"): kwargs[key] = bytes32.fromhex(value[2:])
        else: kwargs[key] = value
    keys = tuple(bytes(AugSchemeMPL.key_gen(bytes([i]) * 32).get_g1()) for i in (1, 2, 3))
    metadata = bytes32(b"\x77" * 32)
    treasury = bytes32(b"\x66" * 32)
    kwargs.update(metadata_root=metadata, royalty_bps=100, royalty_puzhash=treasury)
    inputs.update(royalty_bps=100, royalty_puzhash="0x"+treasury.hex())
    cases = []
    for version in (1, 2):
        for base in (1, 101, 10_000):
            config = PrimaryPurchaseMintConfig(network="testnet11", usd_amount_minor=base,
                technology_fee_bps=100, protocol_treasury_puzhash=treasury, validator_pubkeys=keys,
                provider_id=PRIMARY_PURCHASE_PROVIDER_ID if version == 2 else HISTORICAL_PROVIDER_ID, inventory_version=version)
            result = build_mint_publish_artifacts(**kwargs, primary_purchase=config)
            expected = {}
            for field in fields(result):
                value = getattr(result, field.name)
                if isinstance(value, Program):
                    expected[field.name+"_hex"] = "0x"+bytes(value).hex()
                    expected[field.name+"_hash"] = "0x"+value.get_tree_hash().hex()
                else: expected[field.name] = "0x"+bytes(value).hex()
            cases.append(dict(version=version, base=base, fee=(base+99)//100, subtotal=base+(base+99)//100, expected=expected))
    return dict(inputs=inputs, metadataRoot="0x"+metadata.hex(), treasury="0x"+treasury.hex(),
                validators=["0x"+key.hex() for key in keys], cases=cases)


def constants():
    lines = ["// Generated by protocol/scripts/dump_inventory_mint_fixtures.py; historical modules preserved.\n"]
    lines.append(f"export const INVENTORY_PROVIDER_ID = '0x{PRIMARY_PURCHASE_PROVIDER_ID.hex()}';\n")
    lines.append(f"export const INVENTORY_P2_VAULT_HASH = '0x{load_puzzle('p2_vault.clsp').get_tree_hash().hex()}';\n")
    for name, puzzle in (("INVENTORY_V1", "mint_offer_inventory_available_v1.clsp"),
                         ("INVENTORY_V2", "mint_offer_inventory_available_v2.clsp"),
                         ("RESERVED_V5", "mint_offer_delegate_v5.clsp")):
        mod = load_puzzle(puzzle)
        lines.append(f"export const {name}_HEX = '0x{bytes(mod).hex()}';\n")
        lines.append(f"export const {name}_HASH = '0x{mod.get_tree_hash().hex()}';\n")
    return ''.join(lines)


if __name__ == "__main__":
    root = Path(__file__).resolve().parents[1]
    fixture = json.dumps(build_inventory_fixture(), indent=2)+"\n"
    (root/"fixtures/mint-proposal-v2/inventory-mint.fixtures.json").write_text(fixture)
    target = root.parent/"admin-portal/src/app/services/mint-proposal-v2"
    (target/"inventory-mint.fixtures.json").write_text(fixture)
    (target/"inventory-puzzles.ts").write_text(constants())
