"""Generate additive Base test-payment vectors; retain historical fixtures."""
import argparse
import json
from pathlib import Path
from scripts.dump_governance_v2_inventory_fixture import build_fixture
from solslot_puzzles import load_puzzle
from solslot_puzzles.alpha_payment_profile import alpha_payment_profile


def constants():
    lines = ['// Generated by protocol/scripts/dump_base_inventory_fixture.py.\n']
    for name, source in [('INVENTORY_V3', 'mint_offer_inventory_available_v3.clsp'),
                         ('RESERVED_V6', 'mint_offer_delegate_v6.clsp')]:
        puzzle = load_puzzle(source)
        lines.append(f"export const {name}_HEX = '0x{bytes(puzzle).hex()}';\n")
        lines.append(f"export const {name}_HASH = '0x{puzzle.get_tree_hash().hex()}';\n")
    lines.append('export const BASE_TEST_PAYMENT_PROFILE = ' + json.dumps(alpha_payment_profile(), indent=2) + ' as const;\n')
    return ''.join(lines)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--portal', type=Path, required=True)
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    target = args.portal / 'src/app/services/mint-proposal-v2'
    raw = json.dumps(build_fixture(inventory_version=3), indent=2) + '\n'
    name = 'base-inventory.fixture.json'
    for path, content in [(root / 'fixtures/mint-proposal-v2' / name, raw),
                          (target / name, raw), (target / 'base-inventory-puzzles.ts', constants())]:
        # Never overwrite prior generated evidence.
        with path.open('x') as output:
            output.write(content)
